# Generated by Django 6.0.2 on 2026-02-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_historicalcustomgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcustomgroup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalcustomgroup',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcustomgroup',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='CustomGroup',
        ),
        migrations.DeleteModel(
            name='HistoricalCustomGroup',
        ),
    ]
