# Generated by Django 6.0.2 on 2026-02-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalgroupextra',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalgroupextra',
            name='group',
        ),
        migrations.RemoveField(
            model_name='historicalgroupextra',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalgroupextra',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='GroupExtra',
        ),
        migrations.DeleteModel(
            name='HistoricalGroupExtra',
        ),
    ]
